language: ruby
dist: trusty
before_install:
    - gem install bundler
    - cp config/database.yml.travis config/database.yml
    - psql -c 'create database ar_pg_copy_test;' -U postgres

rvm:
  - 2.5.0
  - 3.0
script:
  - bundle exec rspec spec
services:
  postgresql
